### ISSUE TITLE
When Closing a file, it does not get removed from All tab

### ISSUE THREAD

**Issue by VikingAntics** [Loregret/script-panel-plus#6]
When you close a file, it gets removed from the appropriate tab (i.e. Scripts, Docs, Files), but it still shows in the All tab.

After further testing, it seems like the "Close" function is not working 100% correct.  It seems like the save.dat file is getting out of sync with the open/closed files.

**Comment by Loregret** [comment]
I don't have this issue in both Godot 4.0 and Godot 4.1 versions of the plugin. It's probably related to issues that I've already fixed.  

Can you check it with [last versions](https://github.com/Loregret/script-panel-plus/releases)? The version in the Asset library is broken unfortunately, and I'm waiting for moderators to approve new changes.

**Comment by VikingAntics** [comment]
OK, this one is still not fixed.  
To recreate:
1.) Open some GDScript Files
2.) Now, with top bar enabled, click on Search Help and load a help topic, example Node2D.
3.) You should see the Node2D Help Topic in the All tab and the Docs Tab.
4.) Close the Node2D Help Topic.
5.) It disappears from the Docs tab, but there is no way to remove it from the All tab and if you click on it again, it will reload the Node2D Help Topic, but it won't appear in the Docs Tab anymore.  It should not appear in the All tab once it is closed.

Hope this is a clear explanation.

BTW, show Top Bar should probably be ON by default because the Online Docs and Search Help options are in the Top bar.

Thanks for all your help.

**Comment by Loregret** [comment]
I think I fixed this #7

Can you check this issue with the latest release?

**Comment by Loregret** [comment]
@VikingAntics Hello. Can you check the latest release? I think I fixed the issue, but I need confirmation.

**Comment by VikingAntics** [comment]
Looks like it works now.  Thanks for all your support.
